plugins {
    id 'maven-publish'
	id "mmodding.common-base"
}

version = "$project.version+${libs.versions.minecraft.get()}"
group = project.maven_group

subprojects {
	group = project.module_maven_group
}

def included_integrations = allowed_integrations.split(",")

subprojects {
    afterEvaluate {
        // Disable the gen sources task on sub projects
        genSourcesWithVineflower.enabled = false
        genSourcesWithCfr.enabled = false
    }
}

mmodding {
	modules {
		bundle("mmodding-block")
		bundle("mmodding-client-resources")
		bundle("mmodding-config")
		bundle("mmodding-core")
		bundle("mmodding-datagen")
		bundle("mmodding-enchantment")
		bundle("mmodding-fluid")
		bundle("mmodding-inventory")
		bundle("mmodding-item")
		bundle("mmodding-java")
		bundle("mmodding-math")
		bundle("mmodding-network")
		bundle("mmodding-portal")
		bundle("mmodding-sublevel")
		bundle("mmodding-task")
		bundle("mmodding-woodset")
		bundle("mmodding-worldgen")
		rootDir.toPath().resolve("mod-integration").toFile().list().each {
			if (included_integrations.contains(it)) {
				include("mod-integration-mmodding-" + it) // we don't need to depend on it for the root project
			}
		}
	}
}

dependencies {
	api(include(libs.yumi.commons.core.get()))
	api(include(libs.yumi.commons.collections.get()))
	api(include(libs.yumi.commons.event.get()))
}

// Javadocs
/* javadoc {
	options {
		source = "17"
		encoding = "UTF-8"
		charSet = "UTF-8"
		memberLevel = JavadocMemberLevel.PACKAGE
		addStringOption("Xdoclint:none", "-quiet")
		tags(
			'apiNote:a:API Note:',
			'implNote:a:Implementation Note:'
		)
	}

	allprojects.each {
		source(sourceSets.main.allJava)
	}

	classpath = files(sourceSets.main.compileClasspath)
	include("**//*api*//**")
	failOnError = true
} */

// Configure the maven publication
allprojects {
	if (!project.name.contains("mod-integration")) {
		apply plugin: 'maven-publish'

		afterEvaluate {
			publishing {
				publications {
					mavenJava(MavenPublication) {
						from components.java
					}
				}

				// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
				repositories {
					// Add repositories to publish to here.
					// Notice: This block does NOT have the same function as the block in the top level.
					// The repositories here will be used for publishing your artifact, not for
					// retrieving dependencies.
				}
			}
		}
	}
}
