# Gradle Properties
org.gradle.jvmargs = -Xmx2560M
org.gradle.parallel = true
org.gradle.configuration-cache = false

# Mod Properties
version = 0.4.0-alpha
maven_group = com.mmodding
archives_base_name = mmodding_library

# Publication Properties
modrinth_project = J3eDXLuX
curseforge_project = 694928

# Dependencies are managed at gradle/libs.versions.toml
allowed_integrations = trinkets