[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
# For Convention Plugins
fabric_loom = "1.17-SNAPSHOT"
mmodding_gradle = "0.1.6-beta"

java = "25"
minecraft = "26.2-rc-2"
fabric_loader = "0.19.2"

yumi_commons = "2.0.0"

fabric_api = "0.152.1+26.2"

# Mod Integrations
trinkets_updated = "4.0.0-alpha.8+26.1"

[libraries]
# For Convention Plugins
fabric_loom = { module = "net.fabricmc:fabric-loom", version.ref = "fabric_loom" }
mmodding_gradle = { module = "com.mmodding:mmodding-gradle", version.ref = "mmodding_gradle" }

minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

# Yumi Commons
yumi_commons = { module = "dev.yumi.commons:yumi-commons", version.ref = "yumi_commons" }
yumi_commons_core = { module = "dev.yumi.commons:yumi-commons-core", version.ref = "yumi_commons" }
yumi_commons_collections = { module = "dev.yumi.commons:yumi-commons-collections", version.ref = "yumi_commons" }
yumi_commons_event = { module = "dev.yumi.commons:yumi-commons-event", version.ref = "yumi_commons" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

# Mod Integrations
trinkets = { module = "eu.pb4:trinkets", version.ref = "trinkets_updated" }
